### ISSUE TITLE
Apache2 Fails to start

### ISSUE THREAD

**Issue by aspriddell** [edgarrc/MonoUbuntu#1]
OS: Ubuntu server 16.04 Minimal

I believe the issue is to do with using Debian package hosts.
If you change lines 69,70 & 71 using OS specific servers, it will fix the issue

**Comment by aspriddell** [comment]
apache2.service - The Apache HTTP Server
   Loaded: loaded (/lib/systemd/system/apache2.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sat 2018-08-11 08:45:40 UTC; 22s ago
  Process: 9424 ExecStop=/usr/sbin/apachectl stop (code=exited, status=1/FAILURE)
  Process: 9431 ExecStart=/usr/sbin/apachectl start (code=exited, status=1/FAILURE)
 Main PID: 5351 (code=exited, status=0/SUCCESS)
Aug 11 08:45:40 instance-2 systemd[1]: Starting The Apache HTTP Server...
Aug 11 08:45:40 instance-2 apachectl[9431]: apache2: Syntax error on line 146 of /etc/apache2/apache2.conf: Syntax 
error on line 1 of /etc/apache2/mods-enabled/mod_mono.load: Cannot load /usr/lib/apache2/modules/mod_mono.so into s
erver: /usr/lib/apache2/modules/mod_mono.so: undefined symbol: unixd_config
Aug 11 08:45:40 instance-2 apachectl[9431]: Action 'start' failed.
Aug 11 08:45:40 instance-2 apachectl[9431]: The Apache error log may have more information.
Aug 11 08:45:40 instance-2 systemd[1]: apache2.service: Control process exited, code=exited status=1
Aug 11 08:45:40 instance-2 systemd[1]: Failed to start The Apache HTTP Server.
Aug 11 08:45:40 instance-2 systemd[1]: apache2.service: Unit entered failed state.
Aug 11 08:45:40 instance-2 systemd[1]: apache2.service: Failed with result 'exit-code'.

**Comment by edgarrc** [comment]
It is a closed issue but I will leave a comment to let you know that the script is updated to work on Ubuntu 20.04
